### ISSUE TITLE
Error: Argument passed to call that takes no arguments

### ISSUE THREAD

**Issue by bennyyy999** [AvdLee/Roadmap#64]
So when I tried to implement this, i get this error and I don't know what's the problem here.

error: argument passed to call that takes no arguments

I have this configuration:
```
let configuration = RoadmapConfiguration(
    roadmapJSONURL: URL(string: "")!,
    allowVotes: false, // Present the roadmap in read-only mode by setting this to false
    allowSearching: true // Allow users to filter the features list by adding a searchbar
)
```

and this in the View:
```
var body: some View {
    NavigationStack {
        RoadmapView(configuration: configuration)
    }
}
```

It's a project only for iOS, targeting 16.2+.
Using Xcode Version 14.2 (14C18).

**Comment by vdhamer** [comment]
It does compile (Xcode 14.3, iOS 16.3) without your error message. Don't think it is related to Xcode or iOS versions, as the error message is pretty basic.

`struct DummyView: View {
    let configuration = RoadmapConfiguration(
        roadmapJSONURL: URL(string: "")!,
        allowVotes: false, // Present the roadmap in read-only mode by setting this to false
        allowSearching: true // Allow users to filter the features list by adding a searchbar
    )

    var body: some View {
        NavigationStack {
            RoadmapView(configuration: configuration)
        }
    }
}`

**Comment by bennyyy999** [comment]
It works in a new project, but in my current one, it doesn't and I don't have any clue why it shouldn't

**Comment by vdhamer** [comment]
> @vdhamer It works in a new project, but in my current one, it doesn't and I don't have any clue why it shouldn't

Firstly, it would help if you tell us exactly which of the 3 init() calls is giving the problem: RoadmapConfiguration(), RoadmapView() or - highly unlikely - URL(). The compiler doesn’t complain about Roadmap, it complains about at most 1 line of your code. Which?

Secondly, your two projects might be using a different version (commit) of AvdLee/Roadmap. When you add a package to your project, it is creating a local copy. That local copy does NOT get updated automatically. See [explanation](https://telemetrydeck.com/docs/articles/update-package/). But I recommend trying the next option first - you will learn more for the next time it happens ;-)

Thirdly, you can simply point to the offending initializer and right-click to Jump to Definition. Or find it yourself: a version of the Roadmap source files is now part of your project. And see what the compiler is comparing your init() invocation to. Scroll up or down a bit, because there will likely be multiple alternative initializers. If you don’t match any of them, that’s the problem. If you do match one, you found a basic compiler bug - which is very unlikely.

If you want, send me your source files (zip) or put them on GitHub. That (probably?) allows me to recreate the problem locally. On GitHub, you can temporarily make me co-author if you want to keep the files private. I will keep your private code/project confidential. I am far from the guru level, but this looks like something I can help solve.

**Comment by bennyyy999** [comment]
@vdhamer oh yea sorry totally forgot that.
Here is the error:
<img width="948" alt="Screenshot 2023-04-09 at 15 07 12" src="https://user-images.githubusercontent.com/46378741/230774382-8ae0a1d4-3499-49b6-8969-7e46d9460bef.png">

Updating the Package doesn't work, also re-adding it doesn't. Looking through the Package Code I am doing everything I should to and even tried copying code to check it. But the error still persists.

A new project isn't an option either, as we have all the Fastlane and AppStore Connect stuff already setup and don't wanna go through this again. I will look what I can share and upload it to GitHub (we are using Gitlab for the whole).

**Comment by vdhamer** [comment]
@bennyyy999 : Solved.

In line 4 you are defining your own struct/View named `RoadmapView`.
In the body of your `RoadmapView` you include a subview also named 'RoadmapView' which tries to call the view defined in the Roadmap package. But calls your own view instead. If it had worked, you would get infinite recursion and a nasty runtime error:
You can see that if you change `let` to `var`: compile time error gone, but RoadmapView containing itself containing itself containing... (gives a runtime crash).

So you simply should name your own view something like MyRoadmapView. You apparently did that naming correctly in your standalone test app.

This trick would have allowed you to discover this on your own:
> Thirdly, you can simply point to the offending initializer and right-click to Jump to Definition.
You would have presumably jumped to line 4 in the same file.

Another tip: your original help request did not contain the line with the problem. So make a copy of your full app and remove 99.9% until you see the problem vanish (which helps) or to reproduce the problem in a toy app that others can help you with 🤔.

**Comment by bennyyy999** [comment]
@vdhamer God damn, this happened to me once, didn't know this would happen again, thanks so much.

Yea the tip is super helpful, but didn't work in this case, it was always referring to the Package RoadmapView and not my created RoadmapView.
But again, thank you!
